---
title: data-snapper
---
classDiagram

    class TableIntrospector {
        <<interface>>
        +introspect(table_name: &str) TableMetadata
    }

    class PostgresBackend {
        -client: Client
        +new(connection_string: &str) PostgresBackend
    }

    class MicrosoftSQLServerBackend {
        -connection_string: &str
        +new(connection_string: &str) PostgresBackend
    }

    class OracleBackend {
        -connection_string: &str
        +new(connection_string: &str) OracleBackend
    }

%%    TODO class TableExporter {
%%        <<interface>>
%%        +export(table_name: &str):
%%    }

    TableIntrospector <|.. PostgresBackend : implements
    TableIntrospector <|.. MicrosoftSQLServerBackend : implements
    TableIntrospector <|.. OracleBackend : implements