---
title: data-snapper
---
classDiagram

    class SnapperEngine {
        +snap(pivot_table: &str): DataPackage

        -discover_relationships(pivot_table: &str) SnapperGraph
        -extract_data(graph: SnapperGraph) TempDir
    }

    class RelationshipDiscovery {
        +discover(pivot_table: &str) SnapperGraph
    }

    class SnapperGraph {
    }

    class SnapperNode {
    }

    class TableIntrospector {
        <<interface>>
        +introspect(table_name: &str) TableMetadata
    }

    SnapperEngine --> RelationshipDiscovery : discovery
    SnapperEngine ..> SnapperGraph : << traverse >>
    RelationshipDiscovery --> TableIntrospector : introspector
    RelationshipDiscovery ..> SnapperGraph : << produce >>
    SnapperGraph "1" *-- "1..*" SnapperNode : contains